### ISSUE TITLE
the resolution of H2O video is 256*454, why the INTRINSICS is not the same

### ISSUE THREAD

**Issue by kurumi715** [oppo-us-research/USST#6]
INTRINSICS = {'fx': 636.6593017578125, 'fy': 636.251953125, 
              'cx': 635.283881879317, 'cy': 366.8740353496978,  
              'width': 1280.0, 'height': 720.0}

**Comment by Cogito2012** [comment]
@ryz715 
Thanks for your interest in this work! I guess you are wondering why the width and height in INTRINSICS are different from the actual video resolution.

The INTRINSICS parameters and video files are from the H2O dataset without modification. We noted such a difference, but it does not matter in this project.

Actually, the INTRINSICS is only used in the 2D trajectory evaluation process (`trainval_h2o.py: test() --> src/utils_h2o.py: compute_displacement_errors() --> traj_transform() --> XYZ_to_uv()`). Since the trajectories are normalized values in [0,1], the valuation of the projected 2D trajectory is thus in 1280x720 space. However, if you would like to **visualize trajectories on 256x454 video frames**, you need to be very careful here regarding the resolution difference.

Let me know if you have any questions.

**Comment by kurumi715** [comment]
if i would like to visualize the h2o data, what should i do to deal with the INTRINSICS matrix

**Comment by kurumi715** [comment]
i use the preprocess/H2O/visualize.py to visualize the H2O traj, but it seems that the 2D trajs do not match the hand locations of the video, what may be the problem

**Comment by Cogito2012** [comment]
@ryz715 The preprocess script `preprocess/H2O/visualize.py` should work well for visualizing the H2O annotations. See my example here [sub1_h1_4_right1.gif](https://drive.google.com/file/d/1JiA8DBQ-V_7iF5wYjiIcARmm08765z4t/view?usp=sharing). 

You may have noticed the coordinate resizing here [preprocess/H2O/visualize.py#L189](https://github.com/oppo-us-research/USST/blob/bc09a79db8bf947c700ac3edaa38928e1525fc27/preprocess/H2O/visualize.py#L189). It transforms the 2D trajectories of resolution defined in the intrinsics into the 2D trajectories defined in the input video. If you are trying to visualize model outputs, be careful about this step.

**Comment by kurumi715** [comment]
It is certainly visualize well on sub1_h1_4 data, but the program seems not perform well on sub2_h2_4, could you give me some suggestions

**Comment by Cogito2012** [comment]
@ryz715 It could be caused by the inaccurate depth of the hand in the ground truth, provided by the H2O annotations.
